apiVersion: v1
kind: PersistentVolume
metadata:
  name: exam-pv
  labels:
    app: exama
spec:
  storageClassName: standard
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mysql"

